### PR TITLE
Enable a custom builder for `WaveFormBar` instances when using `AnimatedWaveList`

### PR DESCRIPTION
**Pull request by csells**
Fix for https://github.com/agenthesh/waveform/issues/5

### CODE REVIEW

**Comment by agenthesh** [comment]
Hey Chris, that's a really helpful PR, thanks for the work!

**Comment by csells** [comment]
Thanks, @agenthesh. ETA on the updated package on pub.dev?

**Comment by agenthesh** [comment]
Should be up now!

**Comment by csells** [comment]
It is. Thanks!

**Pull request merged**
